---
- name: playbook de configuration du host pour le site web
  hosts: localhost
  become: yes
  tasks:
    - name: Add Microsoft azure-cli repository
      copy:
        dest: /etc/yum.repos.d/azure-cli.repo
        content: |
         [azure-cli]
         name=Azure CLI
         baseurl=https://packages.microsoft.com/yumrepos/azure-cli
         enabled=1
         gpgcheck=0
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    - name: clean
      command: yum clean all
    - package:
        name: "{{ item}}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - git
        - docker
        - azure-cli
    - name: Start service docker, if not started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
