---
- name: playbook de configuration du host pour le site web
  hosts: monsiteweb
  remote_user: azureuser
  become: yes
  tasks:
    - name: Copy a Dockerfile file on the remote machine
      copy:
        src: "{{dockerfile_path}}/Dockerfile"
        dest: /home/azureuser/Dockerfile
    - name: Build image using cache source
      command: docker build --no-cache -t monsiteweb_image .
    - name: remove container
      docker_container:
        name: monsiteweb
        state: absent
    - name: Restart a container
      docker_container:
        name: monsiteweb
        image: monsiteweb_image
        state: started
        ports:
        - "8080:80"